# Generated by Django 3.2 on 2021-04-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('item_id', models.PositiveIntegerField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='model_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Billing_addrs', models.TextField(max_length=100, verbose_name='Billing_Address')),
                ('Phone', models.IntegerField(verbose_name='Phone_Number')),
            ],
        ),
        migrations.CreateModel(
            name='model_purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
            ],
        ),
    ]
