# Generated by Django 3.2 on 2021-04-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_model_cart_model_customer_model_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_customer',
            name='user_name',
            field=models.CharField(max_length=100, null=True, verbose_name='user_name'),
        ),
    ]
