# Generated by Django 3.2 on 2021-04-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20210425_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_cart',
            name='img',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='model_cart',
            name='unit_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
