# Generated by Django 3.2 on 2021-04-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_model_cart_item_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='model_purchase',
            new_name='model_qty',
        ),
    ]
