# Generated by Django 3.2 on 2021-04-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_model_my_orders_model_purchase_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_my_orders',
            name='delivery_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
