# Generated by Django 3.2 on 2021-04-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_model_my_orders_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_my_orders',
            name='delivery_status',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
