# Generated by Django 3.2 on 2021-05-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_model_my_orders_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_purchase_data',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
