# Generated by Django 3.2 on 2021-05-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_alter_model_purchase_data_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_delivery_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('grand_total_all', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='model_purchase_data',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
