# Generated by Django 3.2 on 2021-05-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_auto_20210506_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_delivery_data',
            name='delivery_status',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
