# Generated by Django 3.2 on 2021-05-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_model_delivery_data_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_delivery_data',
            name='bill_addrs',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model_delivery_data',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
