# Generated by Django 3.2 on 2021-05-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_auto_20210506_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_purchase_data',
            name='delivery_status',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
