# Generated by Django 3.2 on 2021-05-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_model_purchase_data_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_delivery_data',
            name='delivery_status',
        ),
    ]
