# Generated by Django 3.2 on 2021-05-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_model_purchase_data_before_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_purchase_data',
            name='bill_wise_profit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
